// <auto-generated />
namespace CG171105_CR150934_desafio01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Pruebaforanea2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pruebaforanea2));
        
        string IMigrationMetadata.Id
        {
            get { return "202109160213407_Prueba foranea 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
