// <auto-generated />
namespace CG171105_CR150934_desafio01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TablaTipoCuentaBancaria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TablaTipoCuentaBancaria));
        
        string IMigrationMetadata.Id
        {
            get { return "202109160150537_Tabla Tipo Cuenta Bancaria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
